# Generated by Django 5.0.1 on 2024-01-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='like',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='gamer',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='users_like', to='crudapp.videogame'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='playlist',
            field=models.ManyToManyField(blank=True, related_name='users_playlist', to='crudapp.videogame'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='users_wishlist', to='crudapp.videogame'),
        ),
    ]
