# Generated by Django 5.0.1 on 2024-01-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_videogame_remove_gamer_dislike_remove_gamer_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='username',
            field=models.CharField(default=0, max_length=15, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
