# Generated by Django 5.0.1 on 2024-01-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_gamer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='password',
            field=models.CharField(default=0, max_length=27, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
